name: Render timelapse video

on:
  push:
    branches:
      - main
    paths:
      - 'archive/**'
      - 'scripts/render_timelapse.py'
      - '.github/workflows/render-timelapse.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Render timelapse video
        run: |
          python3 scripts/render_timelapse.py --fps 12

      - name: Commit and push if updated
        run: |
          if git diff --quiet -- assets/timelapse.mp4; then
            echo "No changes to timelapse video"
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add assets/timelapse.mp4
          git commit -m "Update rendered timelapse video"
          git push
